source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DLinkSDK/deeplink-dev-specs.git'


platform :ios, '13.0'

target 'HttpDNSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HttpDNSDemo
  pod 'HttpDNS'
end
